export {
  syncSubjects,
  syncAssignments,
  getUserLevel,
  convertSubjectToInput,
  convertAssignmentToInput,
  completeLessons,
  syncPendingLessons,
  clearPendingLessons,
  type SyncProgressCallback,
  type SyncSubjectsOptions,
  type SyncSubjectsResult,
  type SyncAssignmentsOptions,
  type SyncAssignmentsResult,
  type LessonToComplete,
  type CompleteLessonsOptions,
  type CompleteLessonsResult,
  type SyncPendingLessonsResult,
} from './syncService';
