export {
  saveApiKey,
  getApiKey,
  clearApiKey,
  hasApiKey,
  type SecureStorageResult,
} from './secureStorage';

export {
  // Database core
  getDatabase,
  initializeDatabase,
  initializeDatabaseWithMigrations,
  closeDatabase,
  executeSql,
  getDatabaseVersion,
  getDatabaseName,
  _resetDatabaseInstance,
  SCHEMA,
  // Subject CRUD
  upsertSubject,
  upsertSubjects,
  getSubjectById,
  getSubjectsByIds,
  getSubjectsByLevel,
  getSubjectsByType,
  getAllSubjects,
  deleteSubject,
  getSubjectCount,
  // Assignment CRUD
  upsertAssignment,
  upsertAssignments,
  getAssignmentById,
  getAssignmentBySubjectId,
  getAvailableReviews,
  getAvailableLessons,
  getAllAssignments,
  deleteAssignment,
  getAssignmentCount,
  getNextReviewTime,
  // Pending Review CRUD
  insertPendingReview,
  getPendingReviewById,
  getAllPendingReviews,
  deletePendingReview,
  deleteAllPendingReviews,
  getPendingReviewCount,
  // Pending Lesson CRUD
  insertPendingLesson,
  insertPendingLessons,
  getPendingLessonById,
  getPendingLessonByAssignmentId,
  getAllPendingLessons,
  deletePendingLesson,
  deletePendingLessonByAssignmentId,
  deleteAllPendingLessons,
  getPendingLessonCount,
  // Sync Status CRUD
  getSyncStatus,
  updateSyncStatus,
  resetSyncStatus,
  getCachedUserLevel,
  saveCachedUserLevel,
  // User Settings CRUD
  getSetting,
  setSetting,
  getAllSettings,
  deleteSetting,
  deleteAllSettings,
  // Learned counts
  getLearnedCount,
  // Upcoming reviews
  getUpcomingReviewsByHour,
  // Data management
  clearAllData,
  // Migrations
  getSchemaVersion,
  runMigrations,
  // Types
  type DatabaseSubject,
  type DatabaseAssignment,
  type DatabasePendingReview,
  type DatabasePendingLesson,
  type DatabaseSyncStatus,
  type SubjectInput,
  type AssignmentInput,
  type PendingReviewInput,
  type PendingLessonInput,
  type SyncStatusUpdate,
  type UpcomingReviewsHourBucket,
  type DatabaseUserSetting,
  type SettingValue,
} from './database';
